GreatKart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add-cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('decrement_qty/<int:item_id>/', views.decrement_qty, name='decrement_qty'),
    path('increment-qty/<int:item_id>/', views.increment_qty, name='increment_qty'),
    path('delete-cart/<int:item_id>/', views.delete_cart, name='delete_cart'),
    path('checkout/', views.checkout, name='checkout')
]

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_details, name='product_details'),
    path('search/', views.search, name='search'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review')
]

carts/models.py
from django.db import models
from store.models import Product, Variation
from accounts.models import Account

# Create your models here.


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product

store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse
from accounts.models import Account
from django.db.models import Avg, Count
# Create your models here.


class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('product_details', args=[self.category.slug, self.slug])

    def average_rating(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def count_reviews(self):
        count = 0
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count

    def __str__(self):
        return self.product_name


variation_category_choice = (
    ('color', 'color'),
    ('size', 'size')
)


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products', max_length=255)

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'

    def __str__(self):
        return self.product.product_name

store/forms.py
from django import forms
from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

carts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from store.models import Product, Variation
from carts.models import Cart, CartItem


# Create your views here.

# by adding an '_' in the front, a function becomes private


def _cart_id(request):
    cart_id = request.session.session_key
    if not cart_id:
        cart_id = request.session.create()
    return cart_id


def cart(request):
    total = 0
    quantity = 0
    tax = 0
    grand_total = 0
    if request.user.is_authenticated:
        cart_items = CartItem.objects.filter(user=request.user, is_active=True)
    else:
        cart_items = CartItem.objects.filter(cart__cart_id=_cart_id(request), is_active=True)
    if cart_items is not None:
        for cart_item in cart_items:
            total += (cart_item.quantity * cart_item.product.price)
            quantity += cart_item.quantity
        tax = (2 * total) / 100
        grand_total += total + tax
    context = {
        'cart_items': cart_items,
        'quantity': quantity,
        'total': total,
        'tax': tax,
        'grand_total': grand_total
    }
    return render(request, 'store/cart.html', context)


# the session id is the cart id


def add_cart(request, product_id):
    if request.method == 'POST':
        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id=_cart_id(request)
            )
            cart.save()
        product = Product.objects.get(id=product_id)
        product_variations = []
        #  key is the variation category
        for key in request.POST:
            value = request.POST[key]
            try:
                product_variation = Variation.objects.get(product=product, variation_category=key, variation_value=value)
                product_variations.append(product_variation)
            except Variation.DoesNotExist:
                pass
        # print(product_variations)
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, product=product)
            if cart_items is not None:
                ex_var_list = []
                cart_sno = []
                for cart_item in cart_items:
                    existing_variations = cart_item.variations.all()
                    ex_var_list.append(list(existing_variations))
                    cart_sno.append(cart_item.id)
                if product_variations in ex_var_list:
                    cart_item_id = cart_sno[ex_var_list.index(product_variations)]
                    item = CartItem.objects.get(id=cart_item_id)
                    item.quantity += 1
                    item.save()
                else:
                    cart_item = CartItem.objects.create(
                        user=request.user,
                        product=product,
                        cart=cart,
                        quantity=1
                    )
                    cart_item.variations.add(*product_variations)
                    cart_item.save()
            else:
                cart_item = CartItem.objects.create(
                    user=request.user,
                    product=product,
                    cart=cart,
                    quantity=1
                )
                cart_item.variations.add(*product_variations)
                cart_item.save()
        else:
            cart_items = CartItem.objects.filter(cart=cart, product=product)
            if cart_items is not None:
                ex_var_list = []
                cart_sno = []
                for cart_item in cart_items:
                    existing_variations = cart_item.variations.all()
                    ex_var_list.append(list(existing_variations))
                    cart_sno.append(cart_item.id)
                if product_variations in ex_var_list:
                    cart_item_id = cart_sno[ex_var_list.index(product_variations)]
                    item = CartItem.objects.get(id=cart_item_id)
                    item.quantity += 1
                    item.save()
                else:
                    cart_item = CartItem.objects.create(
                        product=product,
                        cart=cart,
                        quantity=1
                    )
                    cart_item.variations.add(*product_variations)
                    cart_item.save()
            else:
                cart_item = CartItem.objects.create(
                    user=request.user,
                    product=product,
                    cart=cart,
                    quantity=1
                )
                cart_item.variations.add(*product_variations)
                cart_item.save()
    return redirect('cart')


def increment_qty(request, item_id):
    cart_item = CartItem.objects.get(id=item_id)
    cart_item.quantity += 1
    cart_item.save()
    return redirect('cart')


def decrement_qty(request, item_id):
    cart_item = CartItem.objects.get(id=item_id)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart')


def delete_cart(request, item_id):
    cart_item = CartItem.objects.get(id=item_id)
    cart_item.delete()
    return redirect('cart')


@login_required(login_url='login')
def checkout(request):
    total = 0
    quantity = 0
    tax = 0
    grand_total = 0
    if request.user.is_authenticated:
        cart_items = CartItem.objects.filter(user=request.user)
    else:
        cart_items = CartItem.objects.filter(cart__cart_id=_cart_id(request))
    if cart_items is not None:
        for cart_item in cart_items:
            total += (cart_item.quantity * cart_item.product.price)
            quantity += cart_item.quantity
        tax = (2 * total) / 100
        grand_total = total + tax
    context = {
        'cart_items': cart_items,
        'quantity': quantity,
        'total': total,
        'tax': tax,
        'grand_total': grand_total
    }
    return render(request, 'store/checkout.html', context)

store/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, ReviewRating, ProductGallery
from category.models import Category
from carts.models import CartItem
from carts.views import _cart_id
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import HttpResponse
from django.db.models.query_utils import Q
from .forms import ReviewForm
from django.contrib import messages
from .models import Variation
from orders.models import OrderProduct


# Create your views here.


def store(request, category_slug=None):
    products_display = []
    products_per_page = 1
    if request.method == 'POST':
        size = request.POST['size']
        min_price = int(request.POST['min_price'])
        max_price = int(request.POST['max_price'])
        variations = None
        if category_slug is not None:
            category = get_object_or_404(Category, slug=category_slug)
            products_exist = Variation.objects.filter(product__category=category, variation_category='size', variation_value=size).exists()
            if products_exist:
                variations = Variation.objects.filter(product__category=category, variation_category='size', variation_value=size)
        else:
            products_exist = Variation.objects.filter(variation_category='size', variation_value=size).exists()
            if products_exist:
                variations = Variation.objects.filter(variation_category='size', variation_value=size)
        if variations:
            for variation in variations:
                if min_price <= variation.product.price <= max_price:
                    products_display.append(variation.product)
    else:
        if category_slug is not None:
            category = get_object_or_404(Category, slug=category_slug)
            products_exist = Product.objects.filter(category=category).exists()
            if products_exist:
                products_display = Product.objects.filter(category=category)
        else:
            products_display = Product.objects.all().filter(is_available=True).order_by('id')
            products_per_page = 3
    categories = Category.objects.all()
    paginator = Paginator(products_display, products_per_page)
    page = request.GET.get('page')
    paged_products = paginator.get_page(page)
    context = {
        'categories': categories,
        'products': paged_products,
        'product_count': len(products_display),
        'category_slug': category_slug
    }
    return render(request, 'store/store.html', context)


def product_details(request, category_slug, product_slug):
    try:
        single_product = Product.objects.get(category__slug=category_slug, slug=product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), product=single_product).exists()
    except Exception as e:
        raise e
    if request.user.is_authenticated:
        is_logged_in = True
        is_ordered_product = OrderProduct.objects.filter(user=request.user, product=single_product).exists()
    else:
        is_logged_in = False
        is_ordered_product = False
    is_product_reviews = ReviewRating.objects.filter(product=single_product)
    if is_product_reviews:
        product_reviews = ReviewRating.objects.filter(product=single_product, status=True)
    else:
        product_reviews = None
    product_gallery = ProductGallery.objects.filter(product=single_product)
    context = {
        'product_details': single_product,
        'in_cart': in_cart,
        'is_ordered_product': is_ordered_product,
        'is_logged_in': is_logged_in,
        'product_reviews': product_reviews,
        'product_gallery': product_gallery
    }
    return render(request, 'store/product-detail.html', context)


def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            products = Product.objects.order_by('-created_date').filter(
                Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
            product_count = products.count()
    context = {
        'products': products,
        'product_count': product_count
    }
    return render(request, 'store/store.html', context)


def submit_review(request, product_id):
    # obtains the url of the previous page from where we came to this page
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            reviews = ReviewRating.objects.get(user=request.user, product__id=product_id)
            # instance is simply checking for the past created reviews otherwise it will always create a new review, it should update the review incase the review is added by the same person for the same product
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, 'Thank you! Your review has been updated.')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                product = Product.objects.get(id=product_id)
                data = ReviewRating.objects.create(
                    user=request.user,
                    product=product,
                    subject=form.cleaned_data['subject'],
                    review=form.cleaned_data['review'],
                    rating=form.cleaned_data['rating'],
                    ip=request.META.get('REMOTE_ADDR'),
                )
                data.save()
                messages.success(request, 'Thank you! Your review has been submitted.')
                return redirect(url)

templates/store/product-detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="section-content padding-y bg">
    <div class="container">

        <!-- ============================ COMPONENT 1 ================================= -->
        <div class="card">
            <div class="row no-gutters">
                <aside class="col-md-6">
                    <article class="gallery-wrap">
                        <div class="img-big-wrap mainImage">
                            <center><img src="{{ product_details.image.url }}"></center>
                        </div> <!-- img-big-wrap.// -->

                    </article> <!-- gallery-wrap .end// -->
                    <ul class="thumb">
                        <li>
                            <a href="{{ product_details.image.url }}" target="mainImage"><img src="{{ product_details.image.url }}" alt="Product Image"></a>
                            {% for i in product_gallery %}
                            <a href="{{ i.image.url }}" target="mainImage"><img src="{{ i.image.url }}" alt="Product Image"></a>
                            {% endfor %}
                        </li>
                    </ul>
                </aside>
                <main class="col-md-6 border-left">
                    <form action="{% url 'add_cart' product_details.id %}" method="POST">
                        {% csrf_token %}
                        <article class="content-body">

                            <h2 class="title">{{ product_details.product_name }}</h2>
                            <div class="rating-star">
                                <i class="fa fa-star{% if product_details.average_rating < 0.5 %}-o {% elif product_details.average_rating >= 0.5 and product_details.average_rating < 1 %}-half-o {% endif %}"
                                   aria-hidden="true"></i>
                                <i class="fa fa-star{% if product_details.average_rating < 1.5 %}-o {% elif product_details.average_rating >= 1.5 and product_details.average_rating < 2 %}-half-o {% endif %}"
                                   aria-hidden="true"></i>
                                <i class="fa fa-star{% if product_details.average_rating < 2.5 %}-o {% elif product_details.average_rating >= 2.5 and product_details.average_rating < 3 %}-half-o {% endif %}"
                                   aria-hidden="true"></i>
                                <i class="fa fa-star{% if product_details.average_rating < 3.5 %}-o {% elif product_details.average_rating >= 3.5 and product_details.average_rating < 4 %}-half-o {% endif %}"
                                   aria-hidden="true"></i>
                                <i class="fa fa-star{% if product_details.average_rating < 4.5 %}-o {% elif product_details.average_rating >= 4.5 and product_details.average_rating < 5 %}-half-o {% endif %}"
                                   aria-hidden="true"></i>
                                <span>{{ product_details.count_reviews }} reviews</span>
                            </div>
                            <div class="mb-3">
                                <var class="price h4">${{ product_details.price }}</var>
                            </div>

                            <p>{{ product_details.description }}</p>


                            <hr>
                            <div class="row">
                                <div class="item-option-select">
                                    <h6>Choose Color</h6>
                                    <select name="color" class="form-control" required>
                                        <option value="" disabled selected>Select</option>
                                        {% for i in product_details.variation_set.colors %}
                                        <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}
                                        </option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div> <!-- row.// -->
                            <div class="row">
                                <div class="item-option-select">
                                    <h6>Choose Size</h6>
                                    <select name="size" class="form-control" required>
                                        <option value="" disabled selected>Select</option>
                                        {% for i in product_details.variation_set.sizes %}
                                        <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}
                                        </option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div> <!-- row.// -->
                            <hr>
                            {% if product_details.stock <= 0 %}
                            <h5 class="text-danger">Out of Stock</h5>
                            {% else %}
                            <button class="btn btn-primary" type="submit"><span class="text">Add to cart</span>
                                <i class="fas fa-shopping-cart"></i></button>
                            {% endif %}
                        </article> <!-- product-info-aside .// -->
                    </form>
                </main> <!-- col.// -->
            </div> <!-- row.// -->
        </div> <!-- card.// -->
        <!-- ============================ COMPONENT 1 END .// ================================= -->

        <br>

        <div class="row">
            <div class="col-md-9">


                <form action="{% url 'submit_review' product_details.id %}" method="POST">
                    {% csrf_token %}
                    <h5>Write Your Review</h5>
                    <div>
                        <!-- Rating stars -->
                        <label>How do you rate this product?</label>
                        <br>
                        <div class="rate">
                            <input type="radio" name="rating" id="rating10" value="5" required><label for="rating10"
                                                                                                      title="5"></label>
                            <input type="radio" name="rating" id="rating9" value="4.5" required><label for="rating9"
                                                                                                       title="4.5"
                                                                                                       class="half"></label>
                            <input type="radio" name="rating" id="rating8" value="4" required><label for="rating8"
                                                                                                     title="4"></label>
                            <input type="radio" name="rating" id="rating7" value="3.5" required><label for="rating7"
                                                                                                       title="3.5"
                                                                                                       class="half"></label>
                            <input type="radio" name="rating" id="rating6" value="3" required><label for="rating6"
                                                                                                     title="3"></label>
                            <input type="radio" name="rating" id="rating5" value="2.5" required><label for="rating5"
                                                                                                       title="2.5"
                                                                                                       class="half"></label>
                            <input type="radio" name="rating" id="rating4" value="2" required><label for="rating4"
                                                                                                     title="2"></label>
                            <input type="radio" name="rating" id="rating3" value="1.5" required><label for="rating3"
                                                                                                       title="1.5"
                                                                                                       class="half"></label>
                            <input type="radio" name="rating" id="rating2" value="1" required><label for="rating2"
                                                                                                     title="1"></label>
                            <input type="radio" name="rating" id="rating1" value="0.5" required><label for="rating1"
                                                                                                       title="0.5"
                                                                                                       class="half"></label>
                        </div>
                        <br>
                        Review Title:
                        <input type="text" class="form-control" name="subject">
                        <br>
                        Review:
                        <textarea name="review" rows="4" class="form-control"></textarea>
                        <br>
                        {% if is_logged_in %}
                        {% if is_ordered_product %}
                        <input type="submit" value="Submit Review" class="btn btn-primary">
                        {% else %}
                        <p>You must purchase this product to post a review.</p>
                        {% endif %}
                        {% else %}
                        <p>You must be logged in to post a review. <span><a
                                href="{% url 'login' %}">Login now</a></span></p>
                        {% endif %}
                    </div>
                </form>
                <br>
                {% include 'includes/alerts.html' %}
                <header class="section-heading">
                    <h3>Customer Reviews </h3>
                    <div class="rating-star">
                        <i class="fa fa-star{% if product_details.average_rating < 0.5 %}-o {% elif product_details.average_rating >= 0.5 and product_details.average_rating < 1 %}-half-o {% endif %}"
                           aria-hidden="true"></i>
                        <i class="fa fa-star{% if product_details.average_rating < 1.5 %}-o {% elif product_details.average_rating >= 1.5 and product_details.average_rating < 2 %}-half-o {% endif %}"
                           aria-hidden="true"></i>
                        <i class="fa fa-star{% if product_details.average_rating < 2.5 %}-o {% elif product_details.average_rating >= 2.5 and product_details.average_rating < 3 %}-half-o {% endif %}"
                           aria-hidden="true"></i>
                        <i class="fa fa-star{% if product_details.average_rating < 3.5 %}-o {% elif product_details.average_rating >= 3.5 and product_details.average_rating < 4 %}-half-o {% endif %}"
                           aria-hidden="true"></i>
                        <i class="fa fa-star{% if product_details.average_rating < 4.5 %}-o {% elif product_details.average_rating >= 4.5 and product_details.average_rating < 5 %}-half-o {% endif %}"
                           aria-hidden="true"></i>
                        <span>{{ product_details.count_reviews }} reviews</span>
                    </div>
                </header>
                {% for review in product_reviews %}
                <article class="box mb-3">
                    <div class="icontext w-100">
                        <img src="{% static './images/avatars/avatar1.jpg' %}" class="img-xs icon rounded-circle">
                        <div class="text">
                            <span class="date text-muted float-md-right">{{ review.updated_date }} </span>
                            <h6 class="mb-1">{{ review.user.first_name}} {{review.user.last_name}} </h6>
                            <div class="rating-star">
                              <span>
                                 <i class="fa fa-star{% if review.rating == 0.5 %}-half-o {% elif review.rating < 1 %}-o {% endif %}"
                                    aria-hidden="true"></i>
                                  <i class="fa fa-star{% if review.rating == 1.5 %}-half-o {% elif review.rating < 2 %}-o {% endif %}"
                                     aria-hidden="true"></i>
                                  <i class="fa fa-star{% if review.rating == 2.5 %}-half-o {% elif review.rating < 3 %}-o {% endif %}"
                                     aria-hidden="true"></i>
                                  <i class="fa fa-star{% if review.rating == 3.5 %}-half-o {% elif review.rating < 4 %}-o {% endif %}"
                                     aria-hidden="true"></i>
                                  <i class="fa fa-star{% if review.rating == 4.5 %}-half-o {% elif review.rating < 5 %}-o {% endif %}"
                                     aria-hidden="true"></i>
                              </span>
                            </div>
                        </div>
                    </div> <!-- icontext.// -->
                    <div class="mt-3">
                        <h6>{{ review.subject }}</h6>
                        <p>
                            {{ review.review }}
                        </p>
                    </div>
                </article>
                {% endfor %}


            </div> <!-- col.// -->
        </div> <!-- row.// -->


    </div> <!-- container .//  -->
</section>
{% endblock %}
<!-- ========================= SECTION CONTENT END// ========================= -->